# Generated by Django 3.2.20 on 2023-08-30 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Uzbekiston', max_length=120)),
                ('location', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='Moshinalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Onix', max_length=100)),
                ('colour', models.CharField(default=' ', max_length=50)),
                ('year', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
